//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.11 at 05:56:45 PM MSK 
//


package com.notjuststudio.engine2dgame.xml.room;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="x" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="y" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="view_x" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="view_y" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="view_width" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="view_height" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "x",
    "y",
    "width",
    "height",
    "viewX",
    "viewY",
    "viewWidth",
    "viewHeight"
})
@XmlRootElement(name = "View")
public class View {

    protected float x;
    protected float y;
    @XmlSchemaType(name = "unsignedShort")
    protected int width;
    @XmlSchemaType(name = "unsignedShort")
    protected int height;
    @XmlElement(name = "view_x")
    protected float viewX;
    @XmlElement(name = "view_y")
    protected float viewY;
    @XmlElement(name = "view_width")
    @XmlSchemaType(name = "unsignedShort")
    protected int viewWidth;
    @XmlElement(name = "view_height")
    @XmlSchemaType(name = "unsignedShort")
    protected int viewHeight;

    /**
     * Gets the value of the x property.
     * 
     */
    public float getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     */
    public void setX(float value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     */
    public float getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     */
    public void setY(float value) {
        this.y = value;
    }

    /**
     * Gets the value of the width property.
     * 
     */
    public int getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     */
    public void setWidth(int value) {
        this.width = value;
    }

    /**
     * Gets the value of the height property.
     * 
     */
    public int getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     */
    public void setHeight(int value) {
        this.height = value;
    }

    /**
     * Gets the value of the viewX property.
     * 
     */
    public float getViewX() {
        return viewX;
    }

    /**
     * Sets the value of the viewX property.
     * 
     */
    public void setViewX(float value) {
        this.viewX = value;
    }

    /**
     * Gets the value of the viewY property.
     * 
     */
    public float getViewY() {
        return viewY;
    }

    /**
     * Sets the value of the viewY property.
     * 
     */
    public void setViewY(float value) {
        this.viewY = value;
    }

    /**
     * Gets the value of the viewWidth property.
     * 
     */
    public int getViewWidth() {
        return viewWidth;
    }

    /**
     * Sets the value of the viewWidth property.
     * 
     */
    public void setViewWidth(int value) {
        this.viewWidth = value;
    }

    /**
     * Gets the value of the viewHeight property.
     * 
     */
    public int getViewHeight() {
        return viewHeight;
    }

    /**
     * Sets the value of the viewHeight property.
     * 
     */
    public void setViewHeight(int value) {
        this.viewHeight = value;
    }

}
