//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.03 at 03:29:41 PM MSK 
//


package com.notjuststudio.engine2dgame.xml.back;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.notjuststudio.engine2dgame.xml.back package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Background_QNAME = new QName("", "Background");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.notjuststudio.engine2dgame.xml.back
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Background }
     * 
     */
    public Background createBackground() {
        return new Background();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Background }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Background")
    public JAXBElement<Background> createBackground(Background value) {
        return new JAXBElement<Background>(_Background_QNAME, Background.class, null, value);
    }

}
