//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.08 at 03:13:39 PM MSK 
//


package com.notjuststudio.engine2dgame.xml.ent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Entity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Entity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="event_init" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="event_step" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="event_draw" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="event_destroy" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sprite" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="visible" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="depth" type="{http://www.w3.org/2001/XMLSchema}float" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Entity", propOrder = {
    "eventInit",
    "eventStep",
    "eventDraw",
    "eventDestroy"
})
public class Entity {

    @XmlElement(name = "event_init", required = true)
    protected String eventInit;
    @XmlElement(name = "event_step", required = true)
    protected String eventStep;
    @XmlElement(name = "event_draw", required = true)
    protected String eventDraw;
    @XmlElement(name = "event_destroy", required = true)
    protected String eventDestroy;
    @XmlAttribute(name = "sprite")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String sprite;
    @XmlAttribute(name = "visible")
    protected Boolean visible;
    @XmlAttribute(name = "depth")
    protected Float depth;

    /**
     * Gets the value of the eventInit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventInit() {
        return eventInit;
    }

    /**
     * Sets the value of the eventInit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventInit(String value) {
        this.eventInit = value;
    }

    /**
     * Gets the value of the eventStep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventStep() {
        return eventStep;
    }

    /**
     * Sets the value of the eventStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventStep(String value) {
        this.eventStep = value;
    }

    /**
     * Gets the value of the eventDraw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventDraw() {
        return eventDraw;
    }

    /**
     * Sets the value of the eventDraw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventDraw(String value) {
        this.eventDraw = value;
    }

    /**
     * Gets the value of the eventDestroy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventDestroy() {
        return eventDestroy;
    }

    /**
     * Sets the value of the eventDestroy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventDestroy(String value) {
        this.eventDestroy = value;
    }

    /**
     * Gets the value of the sprite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSprite() {
        return sprite;
    }

    /**
     * Sets the value of the sprite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSprite(String value) {
        this.sprite = value;
    }

    /**
     * Gets the value of the visible property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isVisible() {
        if (visible == null) {
            return true;
        } else {
            return visible;
        }
    }

    /**
     * Sets the value of the visible property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisible(Boolean value) {
        this.visible = value;
    }

    /**
     * Gets the value of the depth property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getDepth() {
        if (depth == null) {
            return  0.0F;
        } else {
            return depth;
        }
    }

    /**
     * Sets the value of the depth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDepth(Float value) {
        this.depth = value;
    }

}
